<?php
Include('connection.php');
echo'<form class="form form--primary" action="passwordUpdate.php" method="post">';
echo'<div class="col-md-6 mb-3">';
echo'<p>';
echo'<label style="font-size: 0.75rem;
    color: #9B9B9B;
    text-transform: uppercase;
    font-weight: 500;
    margin-bottom: 0.25rem;">Old Password</label>';
echo'<input type="password" style="font-weight: 200;" class="form-control" name="o">';
echo'</p>';
echo'</div>';
echo'<div class="col-md-6 mb-3">';
echo'<p>';
echo'<label style="font-size: 0.75rem;
    color: #9B9B9B;
    text-transform: uppercase;
    font-weight: 500;
    margin-bottom: 0.25rem;">New Password</label>';
echo'<input type="password" id="pass" onchange="check_password()" style="font-weight: 200;" class="form-control" name="newp">';
echo'</p>';
echo'</div>';
echo'<div class="col-md-6 mb-3">';
echo'<p>';
echo'<label style="font-size: 0.75rem;
    color: #9B9B9B;
    text-transform: uppercase;
    font-weight: 500;
    margin-bottom: 0.25rem;">Confirm New Password</label>';
echo'<input type="password" id="repass" onchange="check_pass()" style="font-weight: 200;" class="form-control" name="retype">';
echo'</p>';
echo'</div>';
echo'<div class="col-md-6 mb-3">';
echo'<p>';
echo'<input type="submit" class="btn btn-success" name="updateP" name="repassword" id="repass" 
     onchange="check_pass()"value="Submit" style="border-radius: 0;width: 25%;">';
echo'<input type="reset" value="Cancel" class="btn btn--cancel" style="background-color: #9B9B9B; width: 25%;
     margin-left: 4%; border-radius: 0;
    color: white">';
echo'</p>';
echo'</div>';
echo'</div>';
echo'</form>';
